/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import Executive from './Executive';
import PublicListing from './PublicListing';

/**
 * The CompanyDetailsResponse model module.
 * @module model/CompanyDetailsResponse
 * @version 1.0.0
 */
class CompanyDetailsResponse {
    /**
     * Constructs a new <code>CompanyDetailsResponse</code>.
     * @alias module:model/CompanyDetailsResponse
     */
    constructor() { 
        
        CompanyDetailsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompanyDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanyDetailsResponse} obj Optional instance to populate.
     * @return {module:model/CompanyDetailsResponse} The populated <code>CompanyDetailsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyDetailsResponse();

            if (data.hasOwnProperty('websites')) {
                obj['websites'] = ApiClient.convertToType(data['websites'], ['String']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('industry')) {
                obj['industry'] = ApiClient.convertToType(data['industry'], 'Number');
            }
            if (data.hasOwnProperty('company_type')) {
                obj['company_type'] = ApiClient.convertToType(data['company_type'], 'String');
            }
            if (data.hasOwnProperty('founded_year')) {
                obj['founded_year'] = ApiClient.convertToType(data['founded_year'], 'Number');
            }
            if (data.hasOwnProperty('specialties')) {
                obj['specialties'] = ApiClient.convertToType(data['specialties'], ['String']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tagline')) {
                obj['tagline'] = ApiClient.convertToType(data['tagline'], 'String');
            }
            if (data.hasOwnProperty('logo_url')) {
                obj['logo_url'] = ApiClient.convertToType(data['logo_url'], 'String');
            }
            if (data.hasOwnProperty('cover_pic_url')) {
                obj['cover_pic_url'] = ApiClient.convertToType(data['cover_pic_url'], 'String');
            }
            if (data.hasOwnProperty('facebook_url')) {
                obj['facebook_url'] = ApiClient.convertToType(data['facebook_url'], 'String');
            }
            if (data.hasOwnProperty('twitter_url')) {
                obj['twitter_url'] = ApiClient.convertToType(data['twitter_url'], 'String');
            }
            if (data.hasOwnProperty('instagram_url')) {
                obj['instagram_url'] = ApiClient.convertToType(data['instagram_url'], 'String');
            }
            if (data.hasOwnProperty('employee_count')) {
                obj['employee_count'] = ApiClient.convertToType(data['employee_count'], 'Number');
            }
            if (data.hasOwnProperty('employee_count_range_min')) {
                obj['employee_count_range_min'] = ApiClient.convertToType(data['employee_count_range_min'], 'Number');
            }
            if (data.hasOwnProperty('employee_count_range_max')) {
                obj['employee_count_range_max'] = ApiClient.convertToType(data['employee_count_range_max'], 'Number');
            }
            if (data.hasOwnProperty('addresses')) {
                obj['addresses'] = ApiClient.convertToType(data['addresses'], [Address]);
            }
            if (data.hasOwnProperty('executives')) {
                obj['executives'] = ApiClient.convertToType(data['executives'], [Executive]);
            }
            if (data.hasOwnProperty('public_listing')) {
                obj['public_listing'] = ApiClient.convertToType(data['public_listing'], PublicListing);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompanyDetailsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompanyDetailsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['websites'])) {
            throw new Error("Expected the field `websites` to be an array in the JSON data but got " + data['websites']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['company_type'] && !(typeof data['company_type'] === 'string' || data['company_type'] instanceof String)) {
            throw new Error("Expected the field `company_type` to be a primitive type in the JSON string but got " + data['company_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['specialties'])) {
            throw new Error("Expected the field `specialties` to be an array in the JSON data but got " + data['specialties']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['tagline'] && !(typeof data['tagline'] === 'string' || data['tagline'] instanceof String)) {
            throw new Error("Expected the field `tagline` to be a primitive type in the JSON string but got " + data['tagline']);
        }
        // ensure the json data is a string
        if (data['logo_url'] && !(typeof data['logo_url'] === 'string' || data['logo_url'] instanceof String)) {
            throw new Error("Expected the field `logo_url` to be a primitive type in the JSON string but got " + data['logo_url']);
        }
        // ensure the json data is a string
        if (data['cover_pic_url'] && !(typeof data['cover_pic_url'] === 'string' || data['cover_pic_url'] instanceof String)) {
            throw new Error("Expected the field `cover_pic_url` to be a primitive type in the JSON string but got " + data['cover_pic_url']);
        }
        // ensure the json data is a string
        if (data['facebook_url'] && !(typeof data['facebook_url'] === 'string' || data['facebook_url'] instanceof String)) {
            throw new Error("Expected the field `facebook_url` to be a primitive type in the JSON string but got " + data['facebook_url']);
        }
        // ensure the json data is a string
        if (data['twitter_url'] && !(typeof data['twitter_url'] === 'string' || data['twitter_url'] instanceof String)) {
            throw new Error("Expected the field `twitter_url` to be a primitive type in the JSON string but got " + data['twitter_url']);
        }
        // ensure the json data is a string
        if (data['instagram_url'] && !(typeof data['instagram_url'] === 'string' || data['instagram_url'] instanceof String)) {
            throw new Error("Expected the field `instagram_url` to be a primitive type in the JSON string but got " + data['instagram_url']);
        }
        if (data['addresses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['addresses'])) {
                throw new Error("Expected the field `addresses` to be an array in the JSON data but got " + data['addresses']);
            }
            // validate the optional field `addresses` (array)
            for (const item of data['addresses']) {
                Address.validateJSON(item);
            };
        }
        if (data['executives']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['executives'])) {
                throw new Error("Expected the field `executives` to be an array in the JSON data but got " + data['executives']);
            }
            // validate the optional field `executives` (array)
            for (const item of data['executives']) {
                Executive.validateJSON(item);
            };
        }
        // validate the optional field `public_listing`
        if (data['public_listing']) { // data not null
          PublicListing.validateJSON(data['public_listing']);
        }

        return true;
    }


}



/**
 * List of all company website URLs
 * @member {Array.<String>} websites
 */
CompanyDetailsResponse.prototype['websites'] = undefined;

/**
 * A brief description of the company
 * @member {String} description
 */
CompanyDetailsResponse.prototype['description'] = undefined;

/**
 * GICS 8-digit industry code
 * @member {Number} industry
 */
CompanyDetailsResponse.prototype['industry'] = undefined;

/**
 * Type of company
 * @member {module:model/CompanyDetailsResponse.CompanyTypeEnum} company_type
 */
CompanyDetailsResponse.prototype['company_type'] = undefined;

/**
 * Year the company was founded
 * @member {Number} founded_year
 */
CompanyDetailsResponse.prototype['founded_year'] = undefined;

/**
 * List of company specialties
 * @member {Array.<String>} specialties
 */
CompanyDetailsResponse.prototype['specialties'] = undefined;

/**
 * Company name
 * @member {String} name
 */
CompanyDetailsResponse.prototype['name'] = undefined;

/**
 * Company tagline or slogan
 * @member {String} tagline
 */
CompanyDetailsResponse.prototype['tagline'] = undefined;

/**
 * URL to the company logo endpoint
 * @member {String} logo_url
 */
CompanyDetailsResponse.prototype['logo_url'] = undefined;

/**
 * URL to the company's cover/banner image
 * @member {String} cover_pic_url
 */
CompanyDetailsResponse.prototype['cover_pic_url'] = undefined;

/**
 * Facebook profile URL
 * @member {String} facebook_url
 */
CompanyDetailsResponse.prototype['facebook_url'] = undefined;

/**
 * Twitter/X profile URL
 * @member {String} twitter_url
 */
CompanyDetailsResponse.prototype['twitter_url'] = undefined;

/**
 * Instagram profile URL
 * @member {String} instagram_url
 */
CompanyDetailsResponse.prototype['instagram_url'] = undefined;

/**
 * Estimated number of employees
 * @member {Number} employee_count
 */
CompanyDetailsResponse.prototype['employee_count'] = undefined;

/**
 * Lower bound of employee count range (only with include_employee_count=true)
 * @member {Number} employee_count_range_min
 */
CompanyDetailsResponse.prototype['employee_count_range_min'] = undefined;

/**
 * Upper bound of employee count range (only with include_employee_count=true)
 * @member {Number} employee_count_range_max
 */
CompanyDetailsResponse.prototype['employee_count_range_max'] = undefined;

/**
 * List of company addresses
 * @member {Array.<module:model/Address>} addresses
 */
CompanyDetailsResponse.prototype['addresses'] = undefined;

/**
 * List of company executives and board members
 * @member {Array.<module:model/Executive>} executives
 */
CompanyDetailsResponse.prototype['executives'] = undefined;

/**
 * Public company data. Null for private companies.
 * @member {module:model/PublicListing} public_listing
 */
CompanyDetailsResponse.prototype['public_listing'] = undefined;





/**
 * Allowed values for the <code>company_type</code> property.
 * @enum {String}
 * @readonly
 */
CompanyDetailsResponse['CompanyTypeEnum'] = {

    /**
     * value: "PUBLIC_COMPANY"
     * @const
     */
    "PUBLIC_COMPANY": "PUBLIC_COMPANY",

    /**
     * value: "PRIVATELY_HELD"
     * @const
     */
    "PRIVATELY_HELD": "PRIVATELY_HELD",

    /**
     * value: "GOVERNMENT_AGENCY"
     * @const
     */
    "GOVERNMENT_AGENCY": "GOVERNMENT_AGENCY",

    /**
     * value: "NON_PROFIT"
     * @const
     */
    "NON_PROFIT": "NON_PROFIT",

    /**
     * value: "EDUCATIONAL"
     * @const
     */
    "EDUCATIONAL": "EDUCATIONAL",

    /**
     * value: "PARTNERSHIP"
     * @const
     */
    "PARTNERSHIP": "PARTNERSHIP",

    /**
     * value: "SELF_EMPLOYED"
     * @const
     */
    "SELF_EMPLOYED": "SELF_EMPLOYED",

    /**
     * value: "SELF_OWNED"
     * @const
     */
    "SELF_OWNED": "SELF_OWNED"
};



export default CompanyDetailsResponse;

