/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompanyUpdate from './CompanyUpdate';

/**
 * The CompanyUpdatesResponse model module.
 * @module model/CompanyUpdatesResponse
 * @version 1.3.0
 */
class CompanyUpdatesResponse {
    /**
     * Constructs a new <code>CompanyUpdatesResponse</code>.
     * @alias module:model/CompanyUpdatesResponse
     */
    constructor() { 
        
        CompanyUpdatesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompanyUpdatesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanyUpdatesResponse} obj Optional instance to populate.
     * @return {module:model/CompanyUpdatesResponse} The populated <code>CompanyUpdatesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyUpdatesResponse();

            if (data.hasOwnProperty('blogs')) {
                obj['blogs'] = ApiClient.convertToType(data['blogs'], ['String']);
            }
            if (data.hasOwnProperty('x_profile')) {
                obj['x_profile'] = ApiClient.convertToType(data['x_profile'], 'String');
            }
            if (data.hasOwnProperty('updates')) {
                obj['updates'] = ApiClient.convertToType(data['updates'], [CompanyUpdate]);
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompanyUpdatesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompanyUpdatesResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['blogs'])) {
            throw new Error("Expected the field `blogs` to be an array in the JSON data but got " + data['blogs']);
        }
        // ensure the json data is a string
        if (data['x_profile'] && !(typeof data['x_profile'] === 'string' || data['x_profile'] instanceof String)) {
            throw new Error("Expected the field `x_profile` to be a primitive type in the JSON string but got " + data['x_profile']);
        }
        if (data['updates']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['updates'])) {
                throw new Error("Expected the field `updates` to be an array in the JSON data but got " + data['updates']);
            }
            // validate the optional field `updates` (array)
            for (const item of data['updates']) {
                CompanyUpdate.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['timestamp'] && !(typeof data['timestamp'] === 'string' || data['timestamp'] instanceof String)) {
            throw new Error("Expected the field `timestamp` to be a primitive type in the JSON string but got " + data['timestamp']);
        }

        return true;
    }


}



/**
 * List of blog/RSS source URLs discovered for the company
 * @member {Array.<String>} blogs
 */
CompanyUpdatesResponse.prototype['blogs'] = undefined;

/**
 * X/Twitter profile URL for the company
 * @member {String} x_profile
 */
CompanyUpdatesResponse.prototype['x_profile'] = undefined;

/**
 * List of recent updates sorted by date descending
 * @member {Array.<module:model/CompanyUpdate>} updates
 */
CompanyUpdatesResponse.prototype['updates'] = undefined;

/**
 * Timestamp of the API response (ISO 8601 format)
 * @member {String} timestamp
 */
CompanyUpdatesResponse.prototype['timestamp'] = undefined;






export default CompanyUpdatesResponse;

