/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FundingRound from './FundingRound';

/**
 * The CompanyFundingResponse model module.
 * @module model/CompanyFundingResponse
 * @version 1.3.0
 */
class CompanyFundingResponse {
    /**
     * Constructs a new <code>CompanyFundingResponse</code>.
     * @alias module:model/CompanyFundingResponse
     */
    constructor() { 
        
        CompanyFundingResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompanyFundingResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanyFundingResponse} obj Optional instance to populate.
     * @return {module:model/CompanyFundingResponse} The populated <code>CompanyFundingResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyFundingResponse();

            if (data.hasOwnProperty('total_funds_raised_usd')) {
                obj['total_funds_raised_usd'] = ApiClient.convertToType(data['total_funds_raised_usd'], 'Number');
            }
            if (data.hasOwnProperty('funding_rounds')) {
                obj['funding_rounds'] = ApiClient.convertToType(data['funding_rounds'], [FundingRound]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompanyFundingResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompanyFundingResponse</code>.
     */
    static validateJSON(data) {
        if (data['funding_rounds']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['funding_rounds'])) {
                throw new Error("Expected the field `funding_rounds` to be an array in the JSON data but got " + data['funding_rounds']);
            }
            // validate the optional field `funding_rounds` (array)
            for (const item of data['funding_rounds']) {
                FundingRound.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Total funds raised across all rounds in USD
 * @member {Number} total_funds_raised_usd
 */
CompanyFundingResponse.prototype['total_funds_raised_usd'] = undefined;

/**
 * List of funding rounds
 * @member {Array.<module:model/FundingRound>} funding_rounds
 */
CompanyFundingResponse.prototype['funding_rounds'] = undefined;






export default CompanyFundingResponse;

