/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompetitorCompany model module.
 * @module model/CompetitorCompany
 * @version 1.0.0
 */
class CompetitorCompany {
    /**
     * Constructs a new <code>CompetitorCompany</code>.
     * @alias module:model/CompetitorCompany
     */
    constructor() { 
        
        CompetitorCompany.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompetitorCompany</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompetitorCompany} obj Optional instance to populate.
     * @return {module:model/CompetitorCompany} The populated <code>CompetitorCompany</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitorCompany();

            if (data.hasOwnProperty('company_details_url')) {
                obj['company_details_url'] = ApiClient.convertToType(data['company_details_url'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('competition_reason')) {
                obj['competition_reason'] = ApiClient.convertToType(data['competition_reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompetitorCompany</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompetitorCompany</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['company_details_url'] && !(typeof data['company_details_url'] === 'string' || data['company_details_url'] instanceof String)) {
            throw new Error("Expected the field `company_details_url` to be a primitive type in the JSON string but got " + data['company_details_url']);
        }
        // ensure the json data is a string
        if (data['website'] && !(typeof data['website'] === 'string' || data['website'] instanceof String)) {
            throw new Error("Expected the field `website` to be a primitive type in the JSON string but got " + data['website']);
        }
        // ensure the json data is a string
        if (data['competition_reason'] && !(typeof data['competition_reason'] === 'string' || data['competition_reason'] instanceof String)) {
            throw new Error("Expected the field `competition_reason` to be a primitive type in the JSON string but got " + data['competition_reason']);
        }

        return true;
    }


}



/**
 * URL to the Company Details API endpoint for this competitor
 * @member {String} company_details_url
 */
CompetitorCompany.prototype['company_details_url'] = undefined;

/**
 * Company website URL
 * @member {String} website
 */
CompetitorCompany.prototype['website'] = undefined;

/**
 * Why this company is considered a competitor
 * @member {module:model/CompetitorCompany.CompetitionReasonEnum} competition_reason
 */
CompetitorCompany.prototype['competition_reason'] = undefined;





/**
 * Allowed values for the <code>competition_reason</code> property.
 * @enum {String}
 * @readonly
 */
CompetitorCompany['CompetitionReasonEnum'] = {

    /**
     * value: "organic_keyword_overlap"
     * @const
     */
    "organic_keyword_overlap": "organic_keyword_overlap",

    /**
     * value: "product_overlap"
     * @const
     */
    "product_overlap": "product_overlap"
};



export default CompetitorCompany;

