/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateFeedRequestTargetsInner from './CreateFeedRequestTargetsInner';

/**
 * The CreateFeedRequest model module.
 * @module model/CreateFeedRequest
 * @version 1.0.0
 */
class CreateFeedRequest {
    /**
     * Constructs a new <code>CreateFeedRequest</code>.
     * @alias module:model/CreateFeedRequest
     * @param targets {Array.<module:model/CreateFeedRequestTargetsInner>} Initial targets to monitor
     */
    constructor(targets) { 
        
        CreateFeedRequest.initialize(this, targets);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, targets) { 
        obj['targets'] = targets;
        obj['is_public'] = false;
    }

    /**
     * Constructs a <code>CreateFeedRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFeedRequest} obj Optional instance to populate.
     * @return {module:model/CreateFeedRequest} The populated <code>CreateFeedRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFeedRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('targets')) {
                obj['targets'] = ApiClient.convertToType(data['targets'], [CreateFeedRequestTargetsInner]);
            }
            if (data.hasOwnProperty('is_public')) {
                obj['is_public'] = ApiClient.convertToType(data['is_public'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateFeedRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateFeedRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateFeedRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['targets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['targets'])) {
                throw new Error("Expected the field `targets` to be an array in the JSON data but got " + data['targets']);
            }
            // validate the optional field `targets` (array)
            for (const item of data['targets']) {
                CreateFeedRequestTargetsInner.validateJSON(item);
            };
        }

        return true;
    }


}

CreateFeedRequest.RequiredProperties = ["targets"];

/**
 * Feed display name. Auto-generated if not provided.
 * @member {String} name
 */
CreateFeedRequest.prototype['name'] = undefined;

/**
 * Initial targets to monitor
 * @member {Array.<module:model/CreateFeedRequestTargetsInner>} targets
 */
CreateFeedRequest.prototype['targets'] = undefined;

/**
 * Whether the RSS feed should be publicly accessible
 * @member {Boolean} is_public
 * @default false
 */
CreateFeedRequest.prototype['is_public'] = false;






export default CreateFeedRequest;

