/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TargetSettings from './TargetSettings';

/**
 * The CreateFeedRequestTargetsInner model module.
 * @module model/CreateFeedRequestTargetsInner
 * @version 1.0.0
 */
class CreateFeedRequestTargetsInner {
    /**
     * Constructs a new <code>CreateFeedRequestTargetsInner</code>.
     * @alias module:model/CreateFeedRequestTargetsInner
     * @param websiteUrl {String} Website URL of the company to monitor
     */
    constructor(websiteUrl) { 
        
        CreateFeedRequestTargetsInner.initialize(this, websiteUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, websiteUrl) { 
        obj['website_url'] = websiteUrl;
    }

    /**
     * Constructs a <code>CreateFeedRequestTargetsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFeedRequestTargetsInner} obj Optional instance to populate.
     * @return {module:model/CreateFeedRequestTargetsInner} The populated <code>CreateFeedRequestTargetsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFeedRequestTargetsInner();

            if (data.hasOwnProperty('website_url')) {
                obj['website_url'] = ApiClient.convertToType(data['website_url'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = TargetSettings.constructFromObject(data['settings']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateFeedRequestTargetsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateFeedRequestTargetsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateFeedRequestTargetsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['website_url'] && !(typeof data['website_url'] === 'string' || data['website_url'] instanceof String)) {
            throw new Error("Expected the field `website_url` to be a primitive type in the JSON string but got " + data['website_url']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          TargetSettings.validateJSON(data['settings']);
        }

        return true;
    }


}

CreateFeedRequestTargetsInner.RequiredProperties = ["website_url"];

/**
 * Website URL of the company to monitor
 * @member {String} website_url
 */
CreateFeedRequestTargetsInner.prototype['website_url'] = undefined;

/**
 * @member {module:model/TargetSettings} settings
 */
CreateFeedRequestTargetsInner.prototype['settings'] = undefined;






export default CreateFeedRequestTargetsInner;

