/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreditBalanceResponse model module.
 * @module model/CreditBalanceResponse
 * @version 1.0.0
 */
class CreditBalanceResponse {
    /**
     * Constructs a new <code>CreditBalanceResponse</code>.
     * @alias module:model/CreditBalanceResponse
     */
    constructor() { 
        
        CreditBalanceResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreditBalanceResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreditBalanceResponse} obj Optional instance to populate.
     * @return {module:model/CreditBalanceResponse} The populated <code>CreditBalanceResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreditBalanceResponse();

            if (data.hasOwnProperty('credit_balance')) {
                obj['credit_balance'] = ApiClient.convertToType(data['credit_balance'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreditBalanceResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreditBalanceResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Your current credit balance
 * @member {Number} credit_balance
 */
CreditBalanceResponse.prototype['credit_balance'] = undefined;






export default CreditBalanceResponse;

