/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerCompany model module.
 * @module model/CustomerCompany
 * @version 1.0.0
 */
class CustomerCompany {
    /**
     * Constructs a new <code>CustomerCompany</code>.
     * @alias module:model/CustomerCompany
     */
    constructor() { 
        
        CustomerCompany.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerCompany</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerCompany} obj Optional instance to populate.
     * @return {module:model/CustomerCompany} The populated <code>CustomerCompany</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerCompany();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('tagline')) {
                obj['tagline'] = ApiClient.convertToType(data['tagline'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('company_logo_url')) {
                obj['company_logo_url'] = ApiClient.convertToType(data['company_logo_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('industry')) {
                obj['industry'] = ApiClient.convertToType(data['industry'], 'Number');
            }
            if (data.hasOwnProperty('specialties')) {
                obj['specialties'] = ApiClient.convertToType(data['specialties'], ['String']);
            }
            if (data.hasOwnProperty('x_profile')) {
                obj['x_profile'] = ApiClient.convertToType(data['x_profile'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerCompany</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerCompany</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['tagline'] && !(typeof data['tagline'] === 'string' || data['tagline'] instanceof String)) {
            throw new Error("Expected the field `tagline` to be a primitive type in the JSON string but got " + data['tagline']);
        }
        // ensure the json data is a string
        if (data['website'] && !(typeof data['website'] === 'string' || data['website'] instanceof String)) {
            throw new Error("Expected the field `website` to be a primitive type in the JSON string but got " + data['website']);
        }
        // ensure the json data is a string
        if (data['company_logo_url'] && !(typeof data['company_logo_url'] === 'string' || data['company_logo_url'] instanceof String)) {
            throw new Error("Expected the field `company_logo_url` to be a primitive type in the JSON string but got " + data['company_logo_url']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['specialties'])) {
            throw new Error("Expected the field `specialties` to be an array in the JSON data but got " + data['specialties']);
        }
        // ensure the json data is a string
        if (data['x_profile'] && !(typeof data['x_profile'] === 'string' || data['x_profile'] instanceof String)) {
            throw new Error("Expected the field `x_profile` to be a primitive type in the JSON string but got " + data['x_profile']);
        }

        return true;
    }


}



/**
 * Company name
 * @member {String} name
 */
CustomerCompany.prototype['name'] = undefined;

/**
 * A brief description of the company
 * @member {String} description
 */
CustomerCompany.prototype['description'] = undefined;

/**
 * Company tagline or slogan
 * @member {String} tagline
 */
CustomerCompany.prototype['tagline'] = undefined;

/**
 * Company website URL
 * @member {String} website
 */
CustomerCompany.prototype['website'] = undefined;

/**
 * URL to the Company Logo API for this company
 * @member {String} company_logo_url
 */
CustomerCompany.prototype['company_logo_url'] = undefined;

/**
 * Unique identifier
 * @member {String} id
 */
CustomerCompany.prototype['id'] = undefined;

/**
 * GICS 8-digit industry code
 * @member {Number} industry
 */
CustomerCompany.prototype['industry'] = undefined;

/**
 * List of company specialties
 * @member {Array.<String>} specialties
 */
CustomerCompany.prototype['specialties'] = undefined;

/**
 * X (Twitter) profile URL
 * @member {String} x_profile
 */
CustomerCompany.prototype['x_profile'] = undefined;






export default CustomerCompany;

