/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomerCompany from './CustomerCompany';

/**
 * The CustomerListingResponse model module.
 * @module model/CustomerListingResponse
 * @version 1.0.0
 */
class CustomerListingResponse {
    /**
     * Constructs a new <code>CustomerListingResponse</code>.
     * @alias module:model/CustomerListingResponse
     */
    constructor() { 
        
        CustomerListingResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerListingResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerListingResponse} obj Optional instance to populate.
     * @return {module:model/CustomerListingResponse} The populated <code>CustomerListingResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerListingResponse();

            if (data.hasOwnProperty('customers')) {
                obj['customers'] = ApiClient.convertToType(data['customers'], [CustomerCompany]);
            }
            if (data.hasOwnProperty('investors')) {
                obj['investors'] = ApiClient.convertToType(data['investors'], [CustomerCompany]);
            }
            if (data.hasOwnProperty('partner_platforms')) {
                obj['partner_platforms'] = ApiClient.convertToType(data['partner_platforms'], [CustomerCompany]);
            }
            if (data.hasOwnProperty('next_page')) {
                obj['next_page'] = ApiClient.convertToType(data['next_page'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerListingResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerListingResponse</code>.
     */
    static validateJSON(data) {
        if (data['customers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customers'])) {
                throw new Error("Expected the field `customers` to be an array in the JSON data but got " + data['customers']);
            }
            // validate the optional field `customers` (array)
            for (const item of data['customers']) {
                CustomerCompany.validateJSON(item);
            };
        }
        if (data['investors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['investors'])) {
                throw new Error("Expected the field `investors` to be an array in the JSON data but got " + data['investors']);
            }
            // validate the optional field `investors` (array)
            for (const item of data['investors']) {
                CustomerCompany.validateJSON(item);
            };
        }
        if (data['partner_platforms']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['partner_platforms'])) {
                throw new Error("Expected the field `partner_platforms` to be an array in the JSON data but got " + data['partner_platforms']);
            }
            // validate the optional field `partner_platforms` (array)
            for (const item of data['partner_platforms']) {
                CustomerCompany.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page'] && !(typeof data['next_page'] === 'string' || data['next_page'] instanceof String)) {
            throw new Error("Expected the field `next_page` to be a primitive type in the JSON string but got " + data['next_page']);
        }

        return true;
    }


}



/**
 * Companies that are probable customers of the target company
 * @member {Array.<module:model/CustomerCompany>} customers
 */
CustomerListingResponse.prototype['customers'] = undefined;

/**
 * VC firms, PE funds, angel networks that have invested in the target company
 * @member {Array.<module:model/CustomerCompany>} investors
 */
CustomerListingResponse.prototype['investors'] = undefined;

/**
 * Partners, platforms, or service providers the target company uses
 * @member {Array.<module:model/CustomerCompany>} partner_platforms
 */
CustomerListingResponse.prototype['partner_platforms'] = undefined;

/**
 * Pagination URL for the next page of results
 * @member {String} next_page
 */
CustomerListingResponse.prototype['next_page'] = undefined;






export default CustomerListingResponse;

