/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DisposableEmailResponse model module.
 * @module model/DisposableEmailResponse
 * @version 1.0.0
 */
class DisposableEmailResponse {
    /**
     * Constructs a new <code>DisposableEmailResponse</code>.
     * @alias module:model/DisposableEmailResponse
     */
    constructor() { 
        
        DisposableEmailResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DisposableEmailResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DisposableEmailResponse} obj Optional instance to populate.
     * @return {module:model/DisposableEmailResponse} The populated <code>DisposableEmailResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DisposableEmailResponse();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('is_disposable_email')) {
                obj['is_disposable_email'] = ApiClient.convertToType(data['is_disposable_email'], 'Boolean');
            }
            if (data.hasOwnProperty('is_free_email')) {
                obj['is_free_email'] = ApiClient.convertToType(data['is_free_email'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DisposableEmailResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DisposableEmailResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}



/**
 * The email address that was checked
 * @member {String} email
 */
DisposableEmailResponse.prototype['email'] = undefined;

/**
 * Whether the email domain is a known disposable/temporary email provider
 * @member {Boolean} is_disposable_email
 */
DisposableEmailResponse.prototype['is_disposable_email'] = undefined;

/**
 * Whether the email domain is a free email provider
 * @member {Boolean} is_free_email
 */
DisposableEmailResponse.prototype['is_free_email'] = undefined;






export default DisposableEmailResponse;

