/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmployeeCountResponse model module.
 * @module model/EmployeeCountResponse
 * @version 1.0.0
 */
class EmployeeCountResponse {
    /**
     * Constructs a new <code>EmployeeCountResponse</code>.
     * @alias module:model/EmployeeCountResponse
     */
    constructor() { 
        
        EmployeeCountResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmployeeCountResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmployeeCountResponse} obj Optional instance to populate.
     * @return {module:model/EmployeeCountResponse} The populated <code>EmployeeCountResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmployeeCountResponse();

            if (data.hasOwnProperty('employee_count')) {
                obj['employee_count'] = ApiClient.convertToType(data['employee_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmployeeCountResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmployeeCountResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Estimated employee count
 * @member {Number} employee_count
 */
EmployeeCountResponse.prototype['employee_count'] = undefined;






export default EmployeeCountResponse;

