/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeedSummary model module.
 * @module model/FeedSummary
 * @version 1.0.0
 */
class FeedSummary {
    /**
     * Constructs a new <code>FeedSummary</code>.
     * Feed summary returned in list endpoints (without individual targets).
     * @alias module:model/FeedSummary
     */
    constructor() { 
        
        FeedSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FeedSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeedSummary} obj Optional instance to populate.
     * @return {module:model/FeedSummary} The populated <code>FeedSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeedSummary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('is_public')) {
                obj['is_public'] = ApiClient.convertToType(data['is_public'], 'Boolean');
            }
            if (data.hasOwnProperty('is_suspended')) {
                obj['is_suspended'] = ApiClient.convertToType(data['is_suspended'], 'Boolean');
            }
            if (data.hasOwnProperty('suspension_reason')) {
                obj['suspension_reason'] = ApiClient.convertToType(data['suspension_reason'], 'String');
            }
            if (data.hasOwnProperty('rss_url')) {
                obj['rss_url'] = ApiClient.convertToType(data['rss_url'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('target_count')) {
                obj['target_count'] = ApiClient.convertToType(data['target_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FeedSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FeedSummary</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['suspension_reason'] && !(typeof data['suspension_reason'] === 'string' || data['suspension_reason'] instanceof String)) {
            throw new Error("Expected the field `suspension_reason` to be a primitive type in the JSON string but got " + data['suspension_reason']);
        }
        // ensure the json data is a string
        if (data['rss_url'] && !(typeof data['rss_url'] === 'string' || data['rss_url'] instanceof String)) {
            throw new Error("Expected the field `rss_url` to be a primitive type in the JSON string but got " + data['rss_url']);
        }

        return true;
    }


}



/**
 * Unique feed identifier
 * @member {String} id
 */
FeedSummary.prototype['id'] = undefined;

/**
 * Feed display name
 * @member {String} name
 */
FeedSummary.prototype['name'] = undefined;

/**
 * Whether the RSS feed is publicly accessible without a token
 * @member {Boolean} is_public
 */
FeedSummary.prototype['is_public'] = undefined;

/**
 * Whether the feed is currently suspended
 * @member {Boolean} is_suspended
 */
FeedSummary.prototype['is_suspended'] = undefined;

/**
 * Reason for suspension, if suspended
 * @member {String} suspension_reason
 */
FeedSummary.prototype['suspension_reason'] = undefined;

/**
 * URL to the RSS feed
 * @member {String} rss_url
 */
FeedSummary.prototype['rss_url'] = undefined;

/**
 * When the feed was created
 * @member {Date} created_at
 */
FeedSummary.prototype['created_at'] = undefined;

/**
 * Number of active targets in this feed
 * @member {Number} target_count
 */
FeedSummary.prototype['target_count'] = undefined;






export default FeedSummary;

