/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Education from './Education';
import WorkExperience from './WorkExperience';

/**
 * The PersonProfileResponse model module.
 * @module model/PersonProfileResponse
 * @version 1.0.0
 */
class PersonProfileResponse {
    /**
     * Constructs a new <code>PersonProfileResponse</code>.
     * @alias module:model/PersonProfileResponse
     */
    constructor() { 
        
        PersonProfileResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonProfileResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonProfileResponse} obj Optional instance to populate.
     * @return {module:model/PersonProfileResponse} The populated <code>PersonProfileResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonProfileResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('profile_pic_url')) {
                obj['profile_pic_url'] = ApiClient.convertToType(data['profile_pic_url'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('middle_name')) {
                obj['middle_name'] = ApiClient.convertToType(data['middle_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('full_name')) {
                obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('follower_count')) {
                obj['follower_count'] = ApiClient.convertToType(data['follower_count'], 'Number');
            }
            if (data.hasOwnProperty('following_count')) {
                obj['following_count'] = ApiClient.convertToType(data['following_count'], 'Number');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('x_handle')) {
                obj['x_handle'] = ApiClient.convertToType(data['x_handle'], 'String');
            }
            if (data.hasOwnProperty('x_profile_url')) {
                obj['x_profile_url'] = ApiClient.convertToType(data['x_profile_url'], 'String');
            }
            if (data.hasOwnProperty('personal_website')) {
                obj['personal_website'] = ApiClient.convertToType(data['personal_website'], 'String');
            }
            if (data.hasOwnProperty('work_experience')) {
                obj['work_experience'] = ApiClient.convertToType(data['work_experience'], [WorkExperience]);
            }
            if (data.hasOwnProperty('education')) {
                obj['education'] = ApiClient.convertToType(data['education'], [Education]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonProfileResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonProfileResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['profile_pic_url'] && !(typeof data['profile_pic_url'] === 'string' || data['profile_pic_url'] instanceof String)) {
            throw new Error("Expected the field `profile_pic_url` to be a primitive type in the JSON string but got " + data['profile_pic_url']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['middle_name'] && !(typeof data['middle_name'] === 'string' || data['middle_name'] instanceof String)) {
            throw new Error("Expected the field `middle_name` to be a primitive type in the JSON string but got " + data['middle_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['full_name'] && !(typeof data['full_name'] === 'string' || data['full_name'] instanceof String)) {
            throw new Error("Expected the field `full_name` to be a primitive type in the JSON string but got " + data['full_name']);
        }
        // ensure the json data is a string
        if (data['bio'] && !(typeof data['bio'] === 'string' || data['bio'] instanceof String)) {
            throw new Error("Expected the field `bio` to be a primitive type in the JSON string but got " + data['bio']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['x_handle'] && !(typeof data['x_handle'] === 'string' || data['x_handle'] instanceof String)) {
            throw new Error("Expected the field `x_handle` to be a primitive type in the JSON string but got " + data['x_handle']);
        }
        // ensure the json data is a string
        if (data['x_profile_url'] && !(typeof data['x_profile_url'] === 'string' || data['x_profile_url'] instanceof String)) {
            throw new Error("Expected the field `x_profile_url` to be a primitive type in the JSON string but got " + data['x_profile_url']);
        }
        // ensure the json data is a string
        if (data['personal_website'] && !(typeof data['personal_website'] === 'string' || data['personal_website'] instanceof String)) {
            throw new Error("Expected the field `personal_website` to be a primitive type in the JSON string but got " + data['personal_website']);
        }
        if (data['work_experience']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['work_experience'])) {
                throw new Error("Expected the field `work_experience` to be an array in the JSON data but got " + data['work_experience']);
            }
            // validate the optional field `work_experience` (array)
            for (const item of data['work_experience']) {
                WorkExperience.validateJSON(item);
            };
        }
        if (data['education']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['education'])) {
                throw new Error("Expected the field `education` to be an array in the JSON data but got " + data['education']);
            }
            // validate the optional field `education` (array)
            for (const item of data['education']) {
                Education.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Unique person identifier
 * @member {String} id
 */
PersonProfileResponse.prototype['id'] = undefined;

/**
 * Person's slug identifier
 * @member {String} slug
 */
PersonProfileResponse.prototype['slug'] = undefined;

/**
 * Profile picture URL
 * @member {String} profile_pic_url
 */
PersonProfileResponse.prototype['profile_pic_url'] = undefined;

/**
 * First name
 * @member {String} first_name
 */
PersonProfileResponse.prototype['first_name'] = undefined;

/**
 * Middle name
 * @member {String} middle_name
 */
PersonProfileResponse.prototype['middle_name'] = undefined;

/**
 * Last name
 * @member {String} last_name
 */
PersonProfileResponse.prototype['last_name'] = undefined;

/**
 * Full name
 * @member {String} full_name
 */
PersonProfileResponse.prototype['full_name'] = undefined;

/**
 * Professional bio/summary
 * @member {String} bio
 */
PersonProfileResponse.prototype['bio'] = undefined;

/**
 * X/Twitter follower count
 * @member {Number} follower_count
 */
PersonProfileResponse.prototype['follower_count'] = undefined;

/**
 * X/Twitter following count
 * @member {Number} following_count
 */
PersonProfileResponse.prototype['following_count'] = undefined;

/**
 * Country
 * @member {String} country
 */
PersonProfileResponse.prototype['country'] = undefined;

/**
 * City
 * @member {String} city
 */
PersonProfileResponse.prototype['city'] = undefined;

/**
 * State/province
 * @member {String} state
 */
PersonProfileResponse.prototype['state'] = undefined;

/**
 * X/Twitter handle
 * @member {String} x_handle
 */
PersonProfileResponse.prototype['x_handle'] = undefined;

/**
 * X/Twitter profile URL
 * @member {String} x_profile_url
 */
PersonProfileResponse.prototype['x_profile_url'] = undefined;

/**
 * Personal website URL
 * @member {String} personal_website
 */
PersonProfileResponse.prototype['personal_website'] = undefined;

/**
 * Work experience history
 * @member {Array.<module:model/WorkExperience>} work_experience
 */
PersonProfileResponse.prototype['work_experience'] = undefined;

/**
 * Education history
 * @member {Array.<module:model/Education>} education
 */
PersonProfileResponse.prototype['education'] = undefined;






export default PersonProfileResponse;

