/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicListing model module.
 * @module model/PublicListing
 * @version 1.0.0
 */
class PublicListing {
    /**
     * Constructs a new <code>PublicListing</code>.
     * Public company financial data. Only present for public companies.
     * @alias module:model/PublicListing
     */
    constructor() { 
        
        PublicListing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicListing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicListing} obj Optional instance to populate.
     * @return {module:model/PublicListing} The populated <code>PublicListing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicListing();

            if (data.hasOwnProperty('stock_symbol')) {
                obj['stock_symbol'] = ApiClient.convertToType(data['stock_symbol'], 'String');
            }
            if (data.hasOwnProperty('ipo_date')) {
                obj['ipo_date'] = ApiClient.convertToType(data['ipo_date'], 'String');
            }
            if (data.hasOwnProperty('isin')) {
                obj['isin'] = ApiClient.convertToType(data['isin'], 'String');
            }
            if (data.hasOwnProperty('figi')) {
                obj['figi'] = ApiClient.convertToType(data['figi'], 'String');
            }
            if (data.hasOwnProperty('cusip')) {
                obj['cusip'] = ApiClient.convertToType(data['cusip'], 'String');
            }
            if (data.hasOwnProperty('lei')) {
                obj['lei'] = ApiClient.convertToType(data['lei'], 'String');
            }
            if (data.hasOwnProperty('cik')) {
                obj['cik'] = ApiClient.convertToType(data['cik'], 'String');
            }
            if (data.hasOwnProperty('sic_code')) {
                obj['sic_code'] = ApiClient.convertToType(data['sic_code'], 'String');
            }
            if (data.hasOwnProperty('revenue_usd')) {
                obj['revenue_usd'] = ApiClient.convertToType(data['revenue_usd'], 'Number');
            }
            if (data.hasOwnProperty('revenue_captured_at')) {
                obj['revenue_captured_at'] = ApiClient.convertToType(data['revenue_captured_at'], 'String');
            }
            if (data.hasOwnProperty('ebitda_usd')) {
                obj['ebitda_usd'] = ApiClient.convertToType(data['ebitda_usd'], 'Number');
            }
            if (data.hasOwnProperty('ebitda_captured_at')) {
                obj['ebitda_captured_at'] = ApiClient.convertToType(data['ebitda_captured_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PublicListing</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PublicListing</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['stock_symbol'] && !(typeof data['stock_symbol'] === 'string' || data['stock_symbol'] instanceof String)) {
            throw new Error("Expected the field `stock_symbol` to be a primitive type in the JSON string but got " + data['stock_symbol']);
        }
        // ensure the json data is a string
        if (data['ipo_date'] && !(typeof data['ipo_date'] === 'string' || data['ipo_date'] instanceof String)) {
            throw new Error("Expected the field `ipo_date` to be a primitive type in the JSON string but got " + data['ipo_date']);
        }
        // ensure the json data is a string
        if (data['isin'] && !(typeof data['isin'] === 'string' || data['isin'] instanceof String)) {
            throw new Error("Expected the field `isin` to be a primitive type in the JSON string but got " + data['isin']);
        }
        // ensure the json data is a string
        if (data['figi'] && !(typeof data['figi'] === 'string' || data['figi'] instanceof String)) {
            throw new Error("Expected the field `figi` to be a primitive type in the JSON string but got " + data['figi']);
        }
        // ensure the json data is a string
        if (data['cusip'] && !(typeof data['cusip'] === 'string' || data['cusip'] instanceof String)) {
            throw new Error("Expected the field `cusip` to be a primitive type in the JSON string but got " + data['cusip']);
        }
        // ensure the json data is a string
        if (data['lei'] && !(typeof data['lei'] === 'string' || data['lei'] instanceof String)) {
            throw new Error("Expected the field `lei` to be a primitive type in the JSON string but got " + data['lei']);
        }
        // ensure the json data is a string
        if (data['cik'] && !(typeof data['cik'] === 'string' || data['cik'] instanceof String)) {
            throw new Error("Expected the field `cik` to be a primitive type in the JSON string but got " + data['cik']);
        }
        // ensure the json data is a string
        if (data['sic_code'] && !(typeof data['sic_code'] === 'string' || data['sic_code'] instanceof String)) {
            throw new Error("Expected the field `sic_code` to be a primitive type in the JSON string but got " + data['sic_code']);
        }
        // ensure the json data is a string
        if (data['revenue_captured_at'] && !(typeof data['revenue_captured_at'] === 'string' || data['revenue_captured_at'] instanceof String)) {
            throw new Error("Expected the field `revenue_captured_at` to be a primitive type in the JSON string but got " + data['revenue_captured_at']);
        }
        // ensure the json data is a string
        if (data['ebitda_captured_at'] && !(typeof data['ebitda_captured_at'] === 'string' || data['ebitda_captured_at'] instanceof String)) {
            throw new Error("Expected the field `ebitda_captured_at` to be a primitive type in the JSON string but got " + data['ebitda_captured_at']);
        }

        return true;
    }


}



/**
 * Stock ticker symbol
 * @member {String} stock_symbol
 */
PublicListing.prototype['stock_symbol'] = undefined;

/**
 * IPO date in ISO format
 * @member {String} ipo_date
 */
PublicListing.prototype['ipo_date'] = undefined;

/**
 * International Securities Identification Number
 * @member {String} isin
 */
PublicListing.prototype['isin'] = undefined;

/**
 * Financial Instrument Global Identifier
 * @member {String} figi
 */
PublicListing.prototype['figi'] = undefined;

/**
 * CUSIP identifier
 * @member {String} cusip
 */
PublicListing.prototype['cusip'] = undefined;

/**
 * Legal Entity Identifier
 * @member {String} lei
 */
PublicListing.prototype['lei'] = undefined;

/**
 * SEC Central Index Key
 * @member {String} cik
 */
PublicListing.prototype['cik'] = undefined;

/**
 * SEC Standard Industrial Classification code
 * @member {String} sic_code
 */
PublicListing.prototype['sic_code'] = undefined;

/**
 * Annual revenue in USD
 * @member {Number} revenue_usd
 */
PublicListing.prototype['revenue_usd'] = undefined;

/**
 * Date when revenue data was captured (ISO format)
 * @member {String} revenue_captured_at
 */
PublicListing.prototype['revenue_captured_at'] = undefined;

/**
 * EBITDA in USD
 * @member {Number} ebitda_usd
 */
PublicListing.prototype['ebitda_usd'] = undefined;

/**
 * Date when EBITDA data was captured (ISO format)
 * @member {String} ebitda_captured_at
 */
PublicListing.prototype['ebitda_captured_at'] = undefined;






export default PublicListing;

