/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TargetSettings from './TargetSettings';

/**
 * The Target model module.
 * @module model/Target
 * @version 1.0.0
 */
class Target {
    /**
     * Constructs a new <code>Target</code>.
     * @alias module:model/Target
     */
    constructor() { 
        
        Target.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Target</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Target} obj Optional instance to populate.
     * @return {module:model/Target} The populated <code>Target</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Target();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('website_url')) {
                obj['website_url'] = ApiClient.convertToType(data['website_url'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = TargetSettings.constructFromObject(data['settings']);
            }
            if (data.hasOwnProperty('last_polled_at')) {
                obj['last_polled_at'] = ApiClient.convertToType(data['last_polled_at'], 'Date');
            }
            if (data.hasOwnProperty('is_baseline_complete')) {
                obj['is_baseline_complete'] = ApiClient.convertToType(data['is_baseline_complete'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Target</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Target</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['website_url'] && !(typeof data['website_url'] === 'string' || data['website_url'] instanceof String)) {
            throw new Error("Expected the field `website_url` to be a primitive type in the JSON string but got " + data['website_url']);
        }
        // validate the optional field `settings`
        if (data['settings']) { // data not null
          TargetSettings.validateJSON(data['settings']);
        }

        return true;
    }


}



/**
 * Unique target identifier
 * @member {String} id
 */
Target.prototype['id'] = undefined;

/**
 * The website URL being monitored
 * @member {String} website_url
 */
Target.prototype['website_url'] = undefined;

/**
 * @member {module:model/TargetSettings} settings
 */
Target.prototype['settings'] = undefined;

/**
 * When the target was last polled for updates
 * @member {Date} last_polled_at
 */
Target.prototype['last_polled_at'] = undefined;

/**
 * Whether the initial baseline poll has completed. Items are only generated after the baseline.
 * @member {Boolean} is_baseline_complete
 */
Target.prototype['is_baseline_complete'] = undefined;

/**
 * When the target was created
 * @member {Date} created_at
 */
Target.prototype['created_at'] = undefined;






export default Target;

