/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateFeedRequest model module.
 * @module model/UpdateFeedRequest
 * @version 1.0.0
 */
class UpdateFeedRequest {
    /**
     * Constructs a new <code>UpdateFeedRequest</code>.
     * @alias module:model/UpdateFeedRequest
     */
    constructor() { 
        
        UpdateFeedRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateFeedRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateFeedRequest} obj Optional instance to populate.
     * @return {module:model/UpdateFeedRequest} The populated <code>UpdateFeedRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateFeedRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('is_public')) {
                obj['is_public'] = ApiClient.convertToType(data['is_public'], 'Boolean');
            }
            if (data.hasOwnProperty('is_suspended')) {
                obj['is_suspended'] = ApiClient.convertToType(data['is_suspended'], 'Boolean');
            }
            if (data.hasOwnProperty('suspension_reason')) {
                obj['suspension_reason'] = ApiClient.convertToType(data['suspension_reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateFeedRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateFeedRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['suspension_reason'] && !(typeof data['suspension_reason'] === 'string' || data['suspension_reason'] instanceof String)) {
            throw new Error("Expected the field `suspension_reason` to be a primitive type in the JSON string but got " + data['suspension_reason']);
        }

        return true;
    }


}



/**
 * New feed name
 * @member {String} name
 */
UpdateFeedRequest.prototype['name'] = undefined;

/**
 * Whether the RSS feed should be publicly accessible
 * @member {Boolean} is_public
 */
UpdateFeedRequest.prototype['is_public'] = undefined;

/**
 * Manually suspend or resume the feed
 * @member {Boolean} is_suspended
 */
UpdateFeedRequest.prototype['is_suspended'] = undefined;

/**
 * Reason for suspension (required when is_suspended=true)
 * @member {module:model/UpdateFeedRequest.SuspensionReasonEnum} suspension_reason
 */
UpdateFeedRequest.prototype['suspension_reason'] = undefined;





/**
 * Allowed values for the <code>suspension_reason</code> property.
 * @enum {String}
 * @readonly
 */
UpdateFeedRequest['SuspensionReasonEnum'] = {

    /**
     * value: "manual"
     * @const
     */
    "manual": "manual"
};



export default UpdateFeedRequest;

