/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkEmailResponse model module.
 * @module model/WorkEmailResponse
 * @version 1.0.0
 */
class WorkEmailResponse {
    /**
     * Constructs a new <code>WorkEmailResponse</code>.
     * @alias module:model/WorkEmailResponse
     * @param workEmail {String} Best-effort work email address. `null` if no public email was found and no email pattern could be inferred from the domain.
     */
    constructor(workEmail) { 
        
        WorkEmailResponse.initialize(this, workEmail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workEmail) { 
        obj['work_email'] = workEmail;
    }

    /**
     * Constructs a <code>WorkEmailResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkEmailResponse} obj Optional instance to populate.
     * @return {module:model/WorkEmailResponse} The populated <code>WorkEmailResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkEmailResponse();

            if (data.hasOwnProperty('work_email')) {
                obj['work_email'] = ApiClient.convertToType(data['work_email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkEmailResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkEmailResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkEmailResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['work_email'] && !(typeof data['work_email'] === 'string' || data['work_email'] instanceof String)) {
            throw new Error("Expected the field `work_email` to be a primitive type in the JSON string but got " + data['work_email']);
        }

        return true;
    }


}

WorkEmailResponse.RequiredProperties = ["work_email"];

/**
 * Best-effort work email address. `null` if no public email was found and no email pattern could be inferred from the domain.
 * @member {String} work_email
 */
WorkEmailResponse.prototype['work_email'] = undefined;






export default WorkEmailResponse;

