/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompetitorListingResponse from '../model/CompetitorListingResponse';
import Error from '../model/Error';

/**
* CompetitorAPI service.
* @module api/CompetitorAPIApi
* @version 1.0.0
*/
export default class CompetitorAPIApi {

    /**
    * Constructs a new CompetitorAPIApi. 
    * @alias module:api/CompetitorAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCompetitorListing operation.
     * @callback module:api/CompetitorAPIApi~getCompetitorListingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetitorListingResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Competitor Listing
     * Discover direct business competitors of a target company. Competitors are identified via organic keyword overlap and AI-powered product comparison.  **Cost:** 2 credits/competitor returned. Minimum 5 credits per request.
     * @param {String} website The website URL or company name of the target company. A website URL (e.g. `https://www.stripe.com`) is strongly recommended for precision.
     * @param {module:api/CompetitorAPIApi~getCompetitorListingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetitorListingResponse}
     */
    getCompetitorListing(website, callback) {
      let postBody = null;
      // verify the required parameter 'website' is set
      if (website === undefined || website === null) {
        throw new Error("Missing the required parameter 'website' when calling getCompetitorListing");
      }

      let pathParams = {
      };
      let queryParams = {
        'website': website
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CompetitorListingResponse;
      return this.apiClient.callApi(
        '/api/v1/competitor/listing', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
