/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompanyDetailsResponse from '../model/CompanyDetailsResponse';
import EmployeeCountResponse from '../model/EmployeeCountResponse';
import Error from '../model/Error';

/**
* CompanyAPI service.
* @module api/CompanyAPIApi
* @version 1.0.0
*/
export default class CompanyAPIApi {

    /**
    * Constructs a new CompanyAPIApi. 
    * @alias module:api/CompanyAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCompanyDetails operation.
     * @callback module:api/CompanyAPIApi~getCompanyDetailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompanyDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Company Details
     * Retrieve detailed company information including description, industry, executives, addresses, and for public companies: financials and stock info.  **Cost:** 2 credits (4 credits if include_employee_count=true)
     * @param {String} website The website URL of the target company
     * @param {Object} opts Optional parameters
     * @param {Boolean} [includeEmployeeCount = false)] Fetch fresh employee count data via web search. Adds 2 credits.
     * @param {module:api/CompanyAPIApi~getCompanyDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompanyDetailsResponse}
     */
    getCompanyDetails(website, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'website' is set
      if (website === undefined || website === null) {
        throw new Error("Missing the required parameter 'website' when calling getCompanyDetails");
      }

      let pathParams = {
      };
      let queryParams = {
        'website': website,
        'include_employee_count': opts['includeEmployeeCount']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CompanyDetailsResponse;
      return this.apiClient.callApi(
        '/api/v1/company/details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCompanyLogo operation.
     * @callback module:api/CompanyAPIApi~getCompanyLogoCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Company Logo
     * Retrieve the logo of a company given its website URL. Returns the logo as a PNG image (128x128).  **Cost:** FREE (0 credits)
     * @param {String} website The website URL of the target company
     * @param {module:api/CompanyAPIApi~getCompanyLogoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    getCompanyLogo(website, callback) {
      let postBody = null;
      // verify the required parameter 'website' is set
      if (website === undefined || website === null) {
        throw new Error("Missing the required parameter 'website' when calling getCompanyLogo");
      }

      let pathParams = {
      };
      let queryParams = {
        'website': website
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['image/png', 'application/json'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/company/logo', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getEmployeeCount operation.
     * @callback module:api/CompanyAPIApi~getEmployeeCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EmployeeCountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Employee Count
     * Get the employee count for a company. Uses web search to find the most recent employee count information.  **Cost:** 2 credits
     * @param {String} website The website URL of the target company
     * @param {module:api/CompanyAPIApi~getEmployeeCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EmployeeCountResponse}
     */
    getEmployeeCount(website, callback) {
      let postBody = null;
      // verify the required parameter 'website' is set
      if (website === undefined || website === null) {
        throw new Error("Missing the required parameter 'website' when calling getEmployeeCount");
      }

      let pathParams = {
      };
      let queryParams = {
        'website': website
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EmployeeCountResponse;
      return this.apiClient.callApi(
        '/api/v1/company/employee-count', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
