/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DisposableEmailResponse from '../model/DisposableEmailResponse';
import Error from '../model/Error';

/**
* ContactAPI service.
* @module api/ContactAPIApi
* @version 1.0.0
*/
export default class ContactAPIApi {

    /**
    * Constructs a new ContactAPIApi. 
    * @alias module:api/ContactAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Disposable Email Checker
     * Check if an email address is a disposable (temporary/throwaway) email or a free email provider.  **Cost:** FREE (0 credits)
     * @param {String} email The email address to check
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/DisposableEmailResponse} and HTTP response
     */
    checkDisposableEmailWithHttpInfo(email) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling checkDisposableEmail");
      }

      let pathParams = {
      };
      let queryParams = {
        'email': email
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DisposableEmailResponse;
      return this.apiClient.callApi(
        '/api/v1/contact/disposable-email', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Disposable Email Checker
     * Check if an email address is a disposable (temporary/throwaway) email or a free email provider.  **Cost:** FREE (0 credits)
     * @param {String} email The email address to check
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/DisposableEmailResponse}
     */
    checkDisposableEmail(email) {
      return this.checkDisposableEmailWithHttpInfo(email)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
