/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DisposableEmailResponse from '../model/DisposableEmailResponse';
import Error from '../model/Error';

/**
* ContactAPI service.
* @module api/ContactAPIApi
* @version 1.0.0
*/
export default class ContactAPIApi {

    /**
    * Constructs a new ContactAPIApi. 
    * @alias module:api/ContactAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the checkDisposableEmail operation.
     * @callback module:api/ContactAPIApi~checkDisposableEmailCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DisposableEmailResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Disposable Email Checker
     * Check if an email address is a disposable (temporary/throwaway) email or a free email provider.  **Cost:** FREE (0 credits)
     * @param {String} email The email address to check
     * @param {module:api/ContactAPIApi~checkDisposableEmailCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DisposableEmailResponse}
     */
    checkDisposableEmail(email, callback) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling checkDisposableEmail");
      }

      let pathParams = {
      };
      let queryParams = {
        'email': email
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DisposableEmailResponse;
      return this.apiClient.callApi(
        '/api/v1/contact/disposable-email', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
