/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CustomerListingResponse from '../model/CustomerListingResponse';
import Error from '../model/Error';

/**
* CustomerAPI service.
* @module api/CustomerAPIApi
* @version 1.0.0
*/
export default class CustomerAPIApi {

    /**
    * Constructs a new CustomerAPIApi. 
    * @alias module:api/CustomerAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Customer Listing
     * Get a list of highly-probable customers, investors, and partners/platforms of a target company, categorized by relationship type.  **Cost:** 1 credit/request + 2 credits/company returned. Credits are charged even when the request returns an empty result.
     * @param {String} website The website URL of the target company
     * @param {Object} opts Optional parameters
     * @param {String} [cursor] Pagination cursor from `next_page` in a previous response
     * @param {Number} [pageSize = 200)] Number of results per page (1-200, default 200)
     * @param {Boolean} [qualityFilter = true)] Filter out low-quality results (junk TLDs and unreachable websites)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CustomerListingResponse} and HTTP response
     */
    getCustomerListingWithHttpInfo(website, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'website' is set
      if (website === undefined || website === null) {
        throw new Error("Missing the required parameter 'website' when calling getCustomerListing");
      }

      let pathParams = {
      };
      let queryParams = {
        'website': website,
        'cursor': opts['cursor'],
        'page_size': opts['pageSize'],
        'quality_filter': opts['qualityFilter']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CustomerListingResponse;
      return this.apiClient.callApi(
        '/api/v1/customer/listing', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Customer Listing
     * Get a list of highly-probable customers, investors, and partners/platforms of a target company, categorized by relationship type.  **Cost:** 1 credit/request + 2 credits/company returned. Credits are charged even when the request returns an empty result.
     * @param {String} website The website URL of the target company
     * @param {Object} opts Optional parameters
     * @param {String} opts.cursor Pagination cursor from `next_page` in a previous response
     * @param {Number} opts.pageSize Number of results per page (1-200, default 200) (default to 200)
     * @param {Boolean} opts.qualityFilter Filter out low-quality results (junk TLDs and unreachable websites) (default to true)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CustomerListingResponse}
     */
    getCustomerListing(website, opts) {
      return this.getCustomerListingWithHttpInfo(website, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
