/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import PersonProfileResponse from '../model/PersonProfileResponse';

/**
* EmployeeAPI service.
* @module api/EmployeeAPIApi
* @version 1.3.0
*/
export default class EmployeeAPIApi {

    /**
    * Constructs a new EmployeeAPIApi. 
    * @alias module:api/EmployeeAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getPersonProfile operation.
     * @callback module:api/EmployeeAPIApi~getPersonProfileCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PersonProfileResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Person Profile Enrichment
     * Enrich a person's professional profile including work experience, education, and social media presence. Provide at least one of the following combinations: - `work_email` - `first_name` + `employer_website` - `employer_website` + `role` - `slug` or `id` for direct lookup  **Cost:** 3 credits
     * @param {Object} opts Optional parameters
     * @param {String} [workEmail] Person's work email address
     * @param {String} [firstName] Person's first name
     * @param {String} [middleName] Person's middle name
     * @param {String} [lastName] Person's last name
     * @param {String} [employerWebsite] Employer's website URL
     * @param {String} [role] Job role/title
     * @param {String} [slug] Person's unique slug identifier (direct lookup)
     * @param {String} [id] Person's unique ID (direct lookup)
     * @param {module:api/EmployeeAPIApi~getPersonProfileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PersonProfileResponse}
     */
    getPersonProfile(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'work_email': opts['workEmail'],
        'first_name': opts['firstName'],
        'middle_name': opts['middleName'],
        'last_name': opts['lastName'],
        'employer_website': opts['employerWebsite'],
        'role': opts['role'],
        'slug': opts['slug'],
        'id': opts['id']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PersonProfileResponse;
      return this.apiClient.callApi(
        '/api/v1/employee/profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
