/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreditBalanceResponse from '../model/CreditBalanceResponse';
import Error from '../model/Error';

/**
* MetaAPI service.
* @module api/MetaAPIApi
* @version 1.0.0
*/
export default class MetaAPIApi {

    /**
    * Constructs a new MetaAPIApi. 
    * @alias module:api/MetaAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * View Credit Balance
     * Get your current credit balance.  **Cost:** FREE (0 credits)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CreditBalanceResponse} and HTTP response
     */
    getCreditBalanceWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreditBalanceResponse;
      return this.apiClient.callApi(
        '/api/v1/meta/credit-balance', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * View Credit Balance
     * Get your current credit balance.  **Cost:** FREE (0 credits)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CreditBalanceResponse}
     */
    getCreditBalance() {
      return this.getCreditBalanceWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
