/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreditBalanceResponse from '../model/CreditBalanceResponse';
import Error from '../model/Error';

/**
* MetaAPI service.
* @module api/MetaAPIApi
* @version 1.0.0
*/
export default class MetaAPIApi {

    /**
    * Constructs a new MetaAPIApi. 
    * @alias module:api/MetaAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCreditBalance operation.
     * @callback module:api/MetaAPIApi~getCreditBalanceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreditBalanceResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View Credit Balance
     * Get your current credit balance.  **Cost:** FREE (0 credits)
     * @param {module:api/MetaAPIApi~getCreditBalanceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreditBalanceResponse}
     */
    getCreditBalance(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreditBalanceResponse;
      return this.apiClient.callApi(
        '/api/v1/meta/credit-balance', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
