/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddTargetRequest from '../model/AddTargetRequest';
import CreateFeedRequest from '../model/CreateFeedRequest';
import Error from '../model/Error';
import Feed from '../model/Feed';
import FeedListResponse from '../model/FeedListResponse';
import MessageResponse from '../model/MessageResponse';
import Target from '../model/Target';
import UpdateFeedRequest from '../model/UpdateFeedRequest';
import UpdateTargetRequest from '../model/UpdateTargetRequest';

/**
* UpdatesAPI service.
* @module api/UpdatesAPIApi
* @version 1.0.0
*/
export default class UpdatesAPIApi {

    /**
    * Constructs a new UpdatesAPIApi. 
    * @alias module:api/UpdatesAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addTarget operation.
     * @callback module:api/UpdatesAPIApi~addTargetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Target} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Target
     * Add a new company target to an existing feed.  **Cost:** FREE (0 credits)
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {module:model/AddTargetRequest} addTargetRequest 
     * @param {module:api/UpdatesAPIApi~addTargetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Target}
     */
    addTarget(feedId, addTargetRequest, callback) {
      let postBody = addTargetRequest;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling addTarget");
      }
      // verify the required parameter 'addTargetRequest' is set
      if (addTargetRequest === undefined || addTargetRequest === null) {
        throw new Error("Missing the required parameter 'addTargetRequest' when calling addTarget");
      }

      let pathParams = {
        'feed_id': feedId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Target;
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}/targets', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createFeed operation.
     * @callback module:api/UpdatesAPIApi~createFeedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Feed} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Feed
     * Create a new monitoring feed with one or more company targets. Each target specifies a company website and which channels to monitor (blog, X/Twitter, website changes).  **Cost:** 3 credits
     * @param {module:model/CreateFeedRequest} createFeedRequest 
     * @param {module:api/UpdatesAPIApi~createFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Feed}
     */
    createFeed(createFeedRequest, callback) {
      let postBody = createFeedRequest;
      // verify the required parameter 'createFeedRequest' is set
      if (createFeedRequest === undefined || createFeedRequest === null) {
        throw new Error("Missing the required parameter 'createFeedRequest' when calling createFeed");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Feed;
      return this.apiClient.callApi(
        '/api/v1/feeds', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteFeed operation.
     * @callback module:api/UpdatesAPIApi~deleteFeedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Feed
     * Soft-delete a feed and all its targets.  **Cost:** FREE (0 credits)
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {module:api/UpdatesAPIApi~deleteFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageResponse}
     */
    deleteFeed(feedId, callback) {
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling deleteFeed");
      }

      let pathParams = {
        'feed_id': feedId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessageResponse;
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTarget operation.
     * @callback module:api/UpdatesAPIApi~deleteTargetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Target
     * Soft-delete a target from a feed.  **Cost:** FREE (0 credits)
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {String} targetId Target identifier (e.g. target_abc123xyz)
     * @param {module:api/UpdatesAPIApi~deleteTargetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageResponse}
     */
    deleteTarget(feedId, targetId, callback) {
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling deleteTarget");
      }
      // verify the required parameter 'targetId' is set
      if (targetId === undefined || targetId === null) {
        throw new Error("Missing the required parameter 'targetId' when calling deleteTarget");
      }

      let pathParams = {
        'feed_id': feedId,
        'target_id': targetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessageResponse;
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}/targets/{target_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFeed operation.
     * @callback module:api/UpdatesAPIApi~getFeedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Feed} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Feed
     * Get a feed with all its targets.  **Cost:** FREE (0 credits)
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {module:api/UpdatesAPIApi~getFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Feed}
     */
    getFeed(feedId, callback) {
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling getFeed");
      }

      let pathParams = {
        'feed_id': feedId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Feed;
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRssFeed operation.
     * @callback module:api/UpdatesAPIApi~getRssFeedCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get RSS Feed
     * Get the RSS 2.0 XML feed for a monitoring feed. Public feeds are accessible without authentication. Private feeds require the `token` query parameter.  **Cost:** FREE (0 credits)  **Authentication:** This endpoint does NOT use Bearer authentication. Private feeds are authenticated via the `token` query parameter, which is included in the `rss_url` returned when creating a feed.
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {Object} opts Optional parameters
     * @param {String} [token] Access token for private feeds (included in rss_url)
     * @param {module:api/UpdatesAPIApi~getRssFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getRssFeed(feedId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling getRssFeed");
      }

      let pathParams = {
        'feed_id': feedId
      };
      let queryParams = {
        'token': opts['token']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/xml', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}/rss.xml', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listFeeds operation.
     * @callback module:api/UpdatesAPIApi~listFeedsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FeedListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Feeds
     * List all feeds for the authenticated account.  **Cost:** FREE (0 credits)
     * @param {module:api/UpdatesAPIApi~listFeedsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FeedListResponse}
     */
    listFeeds(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = FeedListResponse;
      return this.apiClient.callApi(
        '/api/v1/feeds', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateFeed operation.
     * @callback module:api/UpdatesAPIApi~updateFeedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Feed} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Feed
     * Update feed metadata such as name, visibility, or suspension status.  **Cost:** FREE (0 credits)
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {module:model/UpdateFeedRequest} updateFeedRequest 
     * @param {module:api/UpdatesAPIApi~updateFeedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Feed}
     */
    updateFeed(feedId, updateFeedRequest, callback) {
      let postBody = updateFeedRequest;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling updateFeed");
      }
      // verify the required parameter 'updateFeedRequest' is set
      if (updateFeedRequest === undefined || updateFeedRequest === null) {
        throw new Error("Missing the required parameter 'updateFeedRequest' when calling updateFeed");
      }

      let pathParams = {
        'feed_id': feedId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Feed;
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTarget operation.
     * @callback module:api/UpdatesAPIApi~updateTargetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Target} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Target
     * Update monitoring settings for a target.  **Cost:** FREE (0 credits)
     * @param {String} feedId Feed identifier (e.g. feed_abc123xyz)
     * @param {String} targetId Target identifier (e.g. target_abc123xyz)
     * @param {module:model/UpdateTargetRequest} updateTargetRequest 
     * @param {module:api/UpdatesAPIApi~updateTargetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Target}
     */
    updateTarget(feedId, targetId, updateTargetRequest, callback) {
      let postBody = updateTargetRequest;
      // verify the required parameter 'feedId' is set
      if (feedId === undefined || feedId === null) {
        throw new Error("Missing the required parameter 'feedId' when calling updateTarget");
      }
      // verify the required parameter 'targetId' is set
      if (targetId === undefined || targetId === null) {
        throw new Error("Missing the required parameter 'targetId' when calling updateTarget");
      }
      // verify the required parameter 'updateTargetRequest' is set
      if (updateTargetRequest === undefined || updateTargetRequest === null) {
        throw new Error("Missing the required parameter 'updateTargetRequest' when calling updateTarget");
      }

      let pathParams = {
        'feed_id': feedId,
        'target_id': targetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Target;
      return this.apiClient.callApi(
        '/api/v1/feeds/{feed_id}/targets/{target_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
