/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ninjapear);
  }
}(this, function(expect, Ninjapear) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Ninjapear.CompanyDetailsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyDetailsResponse', function() {
    it('should create an instance of CompanyDetailsResponse', function() {
      // uncomment below and update the code to test CompanyDetailsResponse
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be.a(Ninjapear.CompanyDetailsResponse);
    });

    it('should have the property websites (base name: "websites")', function() {
      // uncomment below and update the code to test the property websites
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property industry (base name: "industry")', function() {
      // uncomment below and update the code to test the property industry
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyType (base name: "company_type")', function() {
      // uncomment below and update the code to test the property companyType
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property foundedYear (base name: "founded_year")', function() {
      // uncomment below and update the code to test the property foundedYear
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property specialties (base name: "specialties")', function() {
      // uncomment below and update the code to test the property specialties
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property tagline (base name: "tagline")', function() {
      // uncomment below and update the code to test the property tagline
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property logoUrl (base name: "logo_url")', function() {
      // uncomment below and update the code to test the property logoUrl
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property coverPicUrl (base name: "cover_pic_url")', function() {
      // uncomment below and update the code to test the property coverPicUrl
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property facebookUrl (base name: "facebook_url")', function() {
      // uncomment below and update the code to test the property facebookUrl
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property twitterUrl (base name: "twitter_url")', function() {
      // uncomment below and update the code to test the property twitterUrl
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property instagramUrl (base name: "instagram_url")', function() {
      // uncomment below and update the code to test the property instagramUrl
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property employeeCount (base name: "employee_count")', function() {
      // uncomment below and update the code to test the property employeeCount
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property employeeCountRangeMin (base name: "employee_count_range_min")', function() {
      // uncomment below and update the code to test the property employeeCountRangeMin
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property employeeCountRangeMax (base name: "employee_count_range_max")', function() {
      // uncomment below and update the code to test the property employeeCountRangeMax
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property addresses (base name: "addresses")', function() {
      // uncomment below and update the code to test the property addresses
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property executives (base name: "executives")', function() {
      // uncomment below and update the code to test the property executives
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property publicListing (base name: "public_listing")', function() {
      // uncomment below and update the code to test the property publicListing
      //var instance = new Ninjapear.CompanyDetailsResponse();
      //expect(instance).to.be();
    });

  });

}));
