/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ninjapear);
  }
}(this, function(expect, Ninjapear) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Ninjapear.CompanyUpdatesResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyUpdatesResponse', function() {
    it('should create an instance of CompanyUpdatesResponse', function() {
      // uncomment below and update the code to test CompanyUpdatesResponse
      //var instance = new Ninjapear.CompanyUpdatesResponse();
      //expect(instance).to.be.a(Ninjapear.CompanyUpdatesResponse);
    });

    it('should have the property blogs (base name: "blogs")', function() {
      // uncomment below and update the code to test the property blogs
      //var instance = new Ninjapear.CompanyUpdatesResponse();
      //expect(instance).to.be();
    });

    it('should have the property xProfile (base name: "x_profile")', function() {
      // uncomment below and update the code to test the property xProfile
      //var instance = new Ninjapear.CompanyUpdatesResponse();
      //expect(instance).to.be();
    });

    it('should have the property updates (base name: "updates")', function() {
      // uncomment below and update the code to test the property updates
      //var instance = new Ninjapear.CompanyUpdatesResponse();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new Ninjapear.CompanyUpdatesResponse();
      //expect(instance).to.be();
    });

  });

}));
