/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NinjaPear);
  }
}(this, function(expect, NinjaPear) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NinjaPear.CustomerCompany();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomerCompany', function() {
    it('should create an instance of CustomerCompany', function() {
      // uncomment below and update the code to test CustomerCompany
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be.a(NinjaPear.CustomerCompany);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property tagline (base name: "tagline")', function() {
      // uncomment below and update the code to test the property tagline
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property companyLogoUrl (base name: "company_logo_url")', function() {
      // uncomment below and update the code to test the property companyLogoUrl
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property industry (base name: "industry")', function() {
      // uncomment below and update the code to test the property industry
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property specialties (base name: "specialties")', function() {
      // uncomment below and update the code to test the property specialties
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

    it('should have the property xProfile (base name: "x_profile")', function() {
      // uncomment below and update the code to test the property xProfile
      //var instance = new NinjaPear.CustomerCompany();
      //expect(instance).to.be();
    });

  });

}));
