/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ninjapear);
  }
}(this, function(expect, Ninjapear) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Ninjapear.PersonProfileResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PersonProfileResponse', function() {
    it('should create an instance of PersonProfileResponse', function() {
      // uncomment below and update the code to test PersonProfileResponse
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be.a(Ninjapear.PersonProfileResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property profilePicUrl (base name: "profile_pic_url")', function() {
      // uncomment below and update the code to test the property profilePicUrl
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property middleName (base name: "middle_name")', function() {
      // uncomment below and update the code to test the property middleName
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "full_name")', function() {
      // uncomment below and update the code to test the property fullName
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property bio (base name: "bio")', function() {
      // uncomment below and update the code to test the property bio
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property followerCount (base name: "follower_count")', function() {
      // uncomment below and update the code to test the property followerCount
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property followingCount (base name: "following_count")', function() {
      // uncomment below and update the code to test the property followingCount
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property xHandle (base name: "x_handle")', function() {
      // uncomment below and update the code to test the property xHandle
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property xProfileUrl (base name: "x_profile_url")', function() {
      // uncomment below and update the code to test the property xProfileUrl
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property personalWebsite (base name: "personal_website")', function() {
      // uncomment below and update the code to test the property personalWebsite
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property workExperience (base name: "work_experience")', function() {
      // uncomment below and update the code to test the property workExperience
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

    it('should have the property education (base name: "education")', function() {
      // uncomment below and update the code to test the property education
      //var instance = new Ninjapear.PersonProfileResponse();
      //expect(instance).to.be();
    });

  });

}));
