/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance. 5. Monitor companies for updates (blog posts, X/Twitter posts, website changes) via RSS feeds. 6. Look up detailed company information (description, industry, executives, financials). 7. Get company funding history and investors. 8. Enrich person/employee professional profiles. 9. Discover competitors of any company (by keyword overlap and product overlap).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddTargetRequest from './model/AddTargetRequest';
import Address from './model/Address';
import CompanyDetailsResponse from './model/CompanyDetailsResponse';
import CompanyFundingResponse from './model/CompanyFundingResponse';
import CompanyUpdate from './model/CompanyUpdate';
import CompanyUpdatesResponse from './model/CompanyUpdatesResponse';
import CompetitorCompany from './model/CompetitorCompany';
import CompetitorListingResponse from './model/CompetitorListingResponse';
import CreateFeedRequest from './model/CreateFeedRequest';
import CreateFeedRequestTargetsInner from './model/CreateFeedRequestTargetsInner';
import CreditBalanceResponse from './model/CreditBalanceResponse';
import CustomerCompany from './model/CustomerCompany';
import CustomerListingResponse from './model/CustomerListingResponse';
import DisposableEmailResponse from './model/DisposableEmailResponse';
import Education from './model/Education';
import EmployeeCountResponse from './model/EmployeeCountResponse';
import Error from './model/Error';
import Executive from './model/Executive';
import Feed from './model/Feed';
import FeedListResponse from './model/FeedListResponse';
import FeedSummary from './model/FeedSummary';
import FundingRound from './model/FundingRound';
import Investor from './model/Investor';
import MessageResponse from './model/MessageResponse';
import PersonProfileResponse from './model/PersonProfileResponse';
import PublicListing from './model/PublicListing';
import Target from './model/Target';
import TargetSettings from './model/TargetSettings';
import UpdateFeedRequest from './model/UpdateFeedRequest';
import UpdateTargetRequest from './model/UpdateTargetRequest';
import WorkEmailResponse from './model/WorkEmailResponse';
import WorkExperience from './model/WorkExperience';
import CompanyAPIApi from './api/CompanyAPIApi';
import CompetitorAPIApi from './api/CompetitorAPIApi';
import ContactAPIApi from './api/ContactAPIApi';
import CustomerAPIApi from './api/CustomerAPIApi';
import EmployeeAPIApi from './api/EmployeeAPIApi';
import MetaAPIApi from './api/MetaAPIApi';
import MonitorAPIApi from './api/MonitorAPIApi';


/**
* JavaScript client for the NinjaPear API - B2B data platform for customer discovery.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Ninjapear = require('index'); // See note below*.
* var xxxSvc = new Ninjapear.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Ninjapear.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Ninjapear.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Ninjapear.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddTargetRequest model constructor.
     * @property {module:model/AddTargetRequest}
     */
    AddTargetRequest,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The CompanyDetailsResponse model constructor.
     * @property {module:model/CompanyDetailsResponse}
     */
    CompanyDetailsResponse,

    /**
     * The CompanyFundingResponse model constructor.
     * @property {module:model/CompanyFundingResponse}
     */
    CompanyFundingResponse,

    /**
     * The CompanyUpdate model constructor.
     * @property {module:model/CompanyUpdate}
     */
    CompanyUpdate,

    /**
     * The CompanyUpdatesResponse model constructor.
     * @property {module:model/CompanyUpdatesResponse}
     */
    CompanyUpdatesResponse,

    /**
     * The CompetitorCompany model constructor.
     * @property {module:model/CompetitorCompany}
     */
    CompetitorCompany,

    /**
     * The CompetitorListingResponse model constructor.
     * @property {module:model/CompetitorListingResponse}
     */
    CompetitorListingResponse,

    /**
     * The CreateFeedRequest model constructor.
     * @property {module:model/CreateFeedRequest}
     */
    CreateFeedRequest,

    /**
     * The CreateFeedRequestTargetsInner model constructor.
     * @property {module:model/CreateFeedRequestTargetsInner}
     */
    CreateFeedRequestTargetsInner,

    /**
     * The CreditBalanceResponse model constructor.
     * @property {module:model/CreditBalanceResponse}
     */
    CreditBalanceResponse,

    /**
     * The CustomerCompany model constructor.
     * @property {module:model/CustomerCompany}
     */
    CustomerCompany,

    /**
     * The CustomerListingResponse model constructor.
     * @property {module:model/CustomerListingResponse}
     */
    CustomerListingResponse,

    /**
     * The DisposableEmailResponse model constructor.
     * @property {module:model/DisposableEmailResponse}
     */
    DisposableEmailResponse,

    /**
     * The Education model constructor.
     * @property {module:model/Education}
     */
    Education,

    /**
     * The EmployeeCountResponse model constructor.
     * @property {module:model/EmployeeCountResponse}
     */
    EmployeeCountResponse,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Executive model constructor.
     * @property {module:model/Executive}
     */
    Executive,

    /**
     * The Feed model constructor.
     * @property {module:model/Feed}
     */
    Feed,

    /**
     * The FeedListResponse model constructor.
     * @property {module:model/FeedListResponse}
     */
    FeedListResponse,

    /**
     * The FeedSummary model constructor.
     * @property {module:model/FeedSummary}
     */
    FeedSummary,

    /**
     * The FundingRound model constructor.
     * @property {module:model/FundingRound}
     */
    FundingRound,

    /**
     * The Investor model constructor.
     * @property {module:model/Investor}
     */
    Investor,

    /**
     * The MessageResponse model constructor.
     * @property {module:model/MessageResponse}
     */
    MessageResponse,

    /**
     * The PersonProfileResponse model constructor.
     * @property {module:model/PersonProfileResponse}
     */
    PersonProfileResponse,

    /**
     * The PublicListing model constructor.
     * @property {module:model/PublicListing}
     */
    PublicListing,

    /**
     * The Target model constructor.
     * @property {module:model/Target}
     */
    Target,

    /**
     * The TargetSettings model constructor.
     * @property {module:model/TargetSettings}
     */
    TargetSettings,

    /**
     * The UpdateFeedRequest model constructor.
     * @property {module:model/UpdateFeedRequest}
     */
    UpdateFeedRequest,

    /**
     * The UpdateTargetRequest model constructor.
     * @property {module:model/UpdateTargetRequest}
     */
    UpdateTargetRequest,

    /**
     * The WorkEmailResponse model constructor.
     * @property {module:model/WorkEmailResponse}
     */
    WorkEmailResponse,

    /**
     * The WorkExperience model constructor.
     * @property {module:model/WorkExperience}
     */
    WorkExperience,

    /**
    * The CompanyAPIApi service constructor.
    * @property {module:api/CompanyAPIApi}
    */
    CompanyAPIApi,

    /**
    * The CompetitorAPIApi service constructor.
    * @property {module:api/CompetitorAPIApi}
    */
    CompetitorAPIApi,

    /**
    * The ContactAPIApi service constructor.
    * @property {module:api/ContactAPIApi}
    */
    ContactAPIApi,

    /**
    * The CustomerAPIApi service constructor.
    * @property {module:api/CustomerAPIApi}
    */
    CustomerAPIApi,

    /**
    * The EmployeeAPIApi service constructor.
    * @property {module:api/EmployeeAPIApi}
    */
    EmployeeAPIApi,

    /**
    * The MetaAPIApi service constructor.
    * @property {module:api/MetaAPIApi}
    */
    MetaAPIApi,

    /**
    * The MonitorAPIApi service constructor.
    * @property {module:api/MonitorAPIApi}
    */
    MonitorAPIApi
};
