/**
 * NinjaPear API
 * NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@nubela.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreditBalanceResponse from './model/CreditBalanceResponse';
import CustomerCompany from './model/CustomerCompany';
import CustomerListingResponse from './model/CustomerListingResponse';
import DisposableEmailResponse from './model/DisposableEmailResponse';
import Error from './model/Error';
import CompanyAPIApi from './api/CompanyAPIApi';
import ContactAPIApi from './api/ContactAPIApi';
import CustomerAPIApi from './api/CustomerAPIApi';
import MetaAPIApi from './api/MetaAPIApi';


/**
* NinjaPear is a data platform that seeks to serve as the single source of truth for B2B data, be it to power your data-driven applications or your sales-driven workflow.  As a data client of NinjaPear API, you can: 1. Look up the customers, investors, and partners/platforms of any business globally. 2. (FREE) Retrieve the logo of any company. 3. (FREE) Find out the nature of an email address. 4. (FREE) Check your credit balance..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NinjaPear = require('index'); // See note below*.
* var xxxSvc = new NinjaPear.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NinjaPear.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NinjaPear.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NinjaPear.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreditBalanceResponse model constructor.
     * @property {module:model/CreditBalanceResponse}
     */
    CreditBalanceResponse,

    /**
     * The CustomerCompany model constructor.
     * @property {module:model/CustomerCompany}
     */
    CustomerCompany,

    /**
     * The CustomerListingResponse model constructor.
     * @property {module:model/CustomerListingResponse}
     */
    CustomerListingResponse,

    /**
     * The DisposableEmailResponse model constructor.
     * @property {module:model/DisposableEmailResponse}
     */
    DisposableEmailResponse,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
    * The CompanyAPIApi service constructor.
    * @property {module:api/CompanyAPIApi}
    */
    CompanyAPIApi,

    /**
    * The ContactAPIApi service constructor.
    * @property {module:api/ContactAPIApi}
    */
    ContactAPIApi,

    /**
    * The CustomerAPIApi service constructor.
    * @property {module:api/CustomerAPIApi}
    */
    CustomerAPIApi,

    /**
    * The MetaAPIApi service constructor.
    * @property {module:api/MetaAPIApi}
    */
    MetaAPIApi
};
